### ISSUE TITLE
Project Name Confusion with Mumble (VoIP)

### ISSUE THREAD

**Issue by joshsziegler** [jaeko44/mumble#3]
I ran into your project looking for code related to the (probably) better known VoIP client/server also known as Mumble: 
- [github.com/mumble-voip/mumble](https://github.com/mumble-voip/mumble#mumble---a-voicechat-utility-for-gamers)
- [mumble.info](https://wiki.mumble.info/wiki/Main_Page) 

I just thought you should know since the confusion probably hurts your projects SEO.

Cheers

**Comment by jaeko44** [comment]
Yeah it's fine this isn't a business just an opensource project ;)
